# Generated by Django 3.2 on 2021-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='D:\\Projects\\drf_react\\media/unnamed.png', upload_to='posts'),
        ),
    ]
